---
- import_tasks: sasl-auth.yml
  tags: [kafka, kafka_config, config, sasl, auth]

- name: Create environment file for Kafka systemd service
  template:
    src: kafka.env.j2
    dest: "{{ kafka_conf_dir }}/kafka.env"
    mode: '0644'
  notify: Restart Kafka

- name: Create kafka server properties file
  template:
    src: server.properties.j2
    dest: "{{ kafka_conf_dir }}/server.properties"
    owner: '{{ kafka_user }}'
    group: '{{ kafka_group }}'
    mode: '0644'
  notify: Restart Kafka

- name: Create JMX password file
  template:
    src: jmxremote.password.j2
    dest: "{{ kafka_conf_dir }}/jmxremote.password"
    mode: '0600'
    owner: kafka
    group: kafka
  notify: Restart Kafka
  when: kafka_jmx_enabled and kafka_jmx_username is defined and kafka_jmx_password is defined

- name: Create JMX access file
  template:
    src: jmxremote.access.j2
    dest: "{{ kafka_conf_dir }}/jmxremote.access"
    mode: '0600'
    owner: kafka
    group: kafka
  notify: Restart Kafka
  when: kafka_jmx_enabled and kafka_jmx_username is defined
